apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - image: gcr.io/kolban-test/myimage
    name: mycontainer
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP